# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f8868ddc0fd5ac973110a5319c2ab7f8e5c1aa2f92459f7e8f756afa298dcaaf744b22e879fc23c851c00676cc63f4d72e5eded4efec56046261818e9a75fb7

test:
  secret_key_base: 2d471acd0f49334e93284e4d75a0ba701f01c12555d1768c34e98b65009bdff7f8bcf006089c919dd263d653311c935819d9772f88dde32f53422d8fcfe42c06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
